import random

print("              _________________      ____         __________               ")
print("*       *    /                 |    /    \    *  |          \              ")
print(" *          /    ______   _____| * /      \      |    ___    |     *     * ")
print("            \    \    |   |       /   /\   \     |   |___>   |             ")
print("          *  \    \   |   |      /   /__\   \  * |         _/             *")
print("*     ________>    |  |   | *   /            \   |   |\    \_______    *   ")
print("     |            /   |   |    /    ______    \  |   | \           |       ")
print("     |___________/    |___|   /____/      \____\ |___|  \__________|    *  ")
print(" *    _____    __  * _____   ____      *  __________   *  _________        ")
print("      \    \  /  \  /    /  /    \       |          \    /         |      *")
print("       \    \/    \/    /  /      \      |    ___    |  /    ______|  *    ")
print("        \              /  /   /\   \ *   |   |___>   |  \    \             ")
print(" *       \            /  /   /__\   \    |         _/*   \    \            ")
print("          \    /\    /  /            \   |   |\    \______>    |   *       ")
print("           \  /  \  /  /    ______    \  |   | \              /          * ")
print("*       *   \/    \/  /____/      \____\ |___|  \____________/         \n\n")
print("  *********************************************************************    ")
print("  ************** Bem Vindo ao Teste Jedi de Advinhação!!! *************    ")
print("  * Utilize a FORÇA para advinhar o Número Secreto que vai de 1 a 100 *    ")
print("  *********************************************************************  \n")
 
numero_secreto = random.randrange(1, 101)
rodada = 1
loop_nivel = 1
pontos = 1000

while loop_nivel < 2:
    nivel = input("Defina o grau de dificuldade do Teste: 1 - Padawan, 2 - Jedi, 3 - Mestre Jedi\n")
    if nivel == "1":
        total_tentativa = 15
        print("Muito bem jovem padawan, você terá 15 chances para acertar, que a Força esteja com você.\n")
        break
    elif nivel == "2":
        total_tentativa = 10
        print("Vamos lá Jedi! Você terá 10 chances para acertar, que a Força esteja com você.\n")
        break
    elif nivel == "3":
        total_tentativa = 5
        print("                                                                                          __.-._")
        print("                                                                                          '-._\"7'")
        print("                                                                                           /'.-c")
        print("Mestre Jedi você terá apenas 5 chances. Lembre-se: \"Faça...ou não faça. Tentativa não há\"  |  /T")
        print("                                                                                          _)_/LI\n")
        break
    else:
        print("Só aceitamos 1, 2 ou 3 como resposta para definir o grau de dificuldade do Teste!\n")
        continue

for rodada in range(1, total_tentativa + 1):
    print(numero_secreto)    #-- Desative este comentário para visualizar o número secreto --
    print("Tentiva {} de {}".format(rodada, total_tentativa))
    chute = int(input("Digite seu palpite: "))
    print("Você escolheu o número:", chute)
    if chute < 1 or chute > 100:
        print("Você deve digitar um valor entre 1 e 100")
        continue
    acertou = chute == numero_secreto
    maior = chute > numero_secreto
    if acertou:
        print("Parabéns!!! Você acertou o número secreto e se tornou um Cavaleiro Jedi")
        break
    elif maior:
        print("Você errou, seu chute foi maior do que o número secreto.")
        pontos_perdidos = abs(numero_secreto - chute)
        pontos = pontos - pontos_perdidos
    else:
        print("Você errou, seu chute foi menor do que o número secreto.")
        pontos_perdidos = abs(numero_secreto - chute)
        pontos = pontos - pontos_perdidos

print("O Teste terminou, o número secreto era {}. Seus níveis de midi-chlorians é {}".format(numero_secreto, pontos))

if acertou is True:
    print("                                   ____                                             ")
    print("                                _.' :  `._                                          ")
    print("                            .-.'`.  ;   .'`.-.                                      ")
    print("                   __      / : ___\ ;  /___ ; \      __                             ")
    print("                 ,'_ \"\"--.:__;\".-.\";: :\".-.\":__;.--\"\" _`,                   ")
    print("                 :' `.t\"\"--.. '<@.`;_  ',@>` ..--\"\"j.' `;                       ")
    print("                      `:-.._J '-.-'L__ `-- ' L_..-;'                                ")
    print("                        \"-.__ ;  .-\"  \"-.  : __.-\"                              ")
    print("                             L ' /.------.\ ' J                                     ")
    print("                             \"-.   \"--\"   .-\"                                   ")
    print("                             __.l\"-:_JL_;-\";.__                                   ")
    print("                          .-j/'.;  ;\"\"\"\"  / .'\"-.                              ")
    print("                        .' /:`. \"-.:     .-\" .';  `.                              ")
    print("                       .-\"  / ;  \"-. \"-..-\" .-\"  :    \"-.                     ")
    print("                    .+\"-.  : :      \"-.__.-\"      ;-._   \                       ")
    print("                    ; \  `.; ;                    : : \"+. ;                        ")
    print("                    :  ;   ; ;                    : ;  : \:                         ")
    print("                   : `.\"-; ;  ;                  :  ;   ,/;                        ")
    print("                    ;    -: ;  :                ;  : .-\"'  :                       ")
    print("                    :\     \  : ;             : \.-\"      :                        ")
    print("                     ;`.    \  ; :            ;.'_..--  / ;                         ")
    print("                     :  \"-.  \"-:  ;          :/.\"      .'  :                     ")
    print("                       \       .-`.\        /t-\"\"  \":-+.   :                     ")
    print("                        `.  .-\"    `l    __/ /`. :  ; ; \  ;                       ")
    print("                          \   .-\" .-\"-.-\"  .' .'j \  /   ;/                      ")
    print("                           \ / .-\"   /.     .'.' ;_:'    ;                         ")
    print("                            :-""-.`./-.'     /    `.___.'                           ")
    print("                                  \ `t  ._  /                                       ")
    print("                                   \"-.t-._:'\n                                     ")
    print("                              ******************************************************")
    print("                              **  VOCÊ FOI APROVADO PELO CONSELHO JEDI NO TESTE!  **")
    print("                              ******************************************************")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
else:
    print("           ________                                                                 ")
    print("      _,.-Y  |  |  Y-._                                                             ")
    print("  .-~\"   ||  |  |  |   \"-.                                                        ")
    print("  I\" \"\"==\"|\" !\"\"! \"|\"[]\"\"|     _____                                     ")
    print("  L__  [] |..------|:   _[----I\" .-{\"-.                                           ")
    print(" I___|  ..| l______|l_ [__L]_[I_/r(=}=-P                                            ")
    print("[L______L_[________]______j~  '-=c_]/=-^                                            ")
    print(" \_I_j.--.\==I|I==_/.--L_]                                                          ")
    print("   [_((==)[`-----\"](==)j                                                           ")
    print("      I--I\"~~\"\"\"~~\"I--I                                                        ")
    print("      |[]|         |[]|                                                             ")
    print("      l__j         l__j                                                             ")
    print("      |!!|         |!!|                                                             ")
    print("      |..|         |..|                                                             ")
    print("      ([])         ([])                                                             ")
    print("      ]--[         ]--[                                                             ")
    print("      [_L]         [_L]                                                             ")
    print("     /|..|\       /|..|\     *******************************************************")
    print("    `=}--{=´     `=}--{=´    **  VOCÊ FOI REPROVADO PELO CONSELHO JEDI NO TESTE!  **")
    print("    .-^--r-^-.   .-^--r-^-.  *******************************************************")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
"""
    print("@@@@@@@@@@@@@@@@@@@@@@WWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMxxxxxxxxxxxxxxxxxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@@")
    print("@@@@@@@@@@@@@@@@WWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMMxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxMxMMxxxMMMMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@@")
    print("@@@@@@@@@@@@@@@WWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxMMMMMMMMMMMMWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@@@")
    print("@@@@@@@@@@@@@WWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMMxxxxxxxxxxxxxxxxxxxxxxxxxnnnxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxMMMMMMMMMWWWWWWWWWWWWWWWWWWW@@@@@@@@@@@@@")
    print("@@@@@@@@@@@@WWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMxxxxxxxxxxxxxxxxxxxxxxnnnnnnnnnnnnnnxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxMMMMMMMMMMMMWWWWWWWWWWWWWWWW@@W@@@@@@@@@")
    print("@@@@@@@@@@@WWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMxxxxxxxxxxxxxnnnnnnxxnnnnnnnnnnnnnnnnnnnnnnxxxxxxxxxnnnnxnnnnxxxxxxxxxxMMMMMMMMMMMMMMWWWWWWWWWWWWWWWW@@@@@@@@@")
    print("@@@@@@@@@@WWWWWWWWWWWWWWWWWMMMMMMMMMMMMMxxxxxxxxxxxxxnnnnnnnnnnnnnnnnnnnnnxxxxnnnnnnnnnnnnnnnnnnnnnnnnnnnnxxxxxxxxMMMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWW@@@@@")
    print("@@@@@@@@@WWWWWWWWWWWWWWWWWMMMMMMMMMMMMxxxxxxxxxxxxnnnnnnnnnnnnnnnnnnnnxxnxi**nxxxxxnnnnnnnnnnnnnnnnnnnnnnnnnnxxxxxxxMMMMMMMMMMMMMWWWWWWWWWWWWWWWWWW@@@@@")
    print("@@@@@@@@@WWWWWWWWWWWWWWWWMMMMMMMMMMMMxxxxxxxxxxxxnnnnnnnnnnnnnnnnnxz  # +*iiznnn#++++++#nxnnnnnnnnnnnnnnnnnnnnnnxxxxxxxxxMMMMMMMMMMMMWWWWWWWWWWWWWWWWW@@")
    print("@@@@@@@WWWWWWWWWWWWWWWWWMMMMMMMMMMMMxxxxxxxnnnnnnnnnnnzzzzzznnnnx  # *+znnnnznnnnnnnnnnz+*#xxnnnnnnnzzzzznnnnnnnnnxxxxxxxxxxxMMMMMMMMWWWWWWWWWWWWWWWWWW@")
    print("@@@@@@@WWWWWWWWWWWWWWWMMMMMMMMMMMMxxxxxxxnnnnnnnnnnnnzzzzzzzzzxz + zxxxnnnnnnnnxnnnnnnnnnz +  # MnzzzzzzzzzzzznnnnnnnnnxxxxxxxxxxMMMMMMMMWWWWWWWWWWWWWWW")
    print("@@@@@@WWWWWWWWWWWWWWMMMMMMMMMMMMxxxxxxxxxnnnnnnnnnzzzzzzzzzzzM  # zxMxxnnnnnxxxxxxxxxxxxxxxnz+MnzzzzzzzzzzzznnnnnnnnnnnxxxxxxxxMMMMMMMMWWWWWWWWWWWWWWWWW")
    print("@@@@@WWWWWWWWWWWWWWMMMMMMMMMMMMxxxxxxxxnnnnnnnnzzzzzzzzzzzzzWznMMxxnnnxxxMWWWMMMMMMMxxxxxxn  # WnzzzzzzzzzzzzznnnnnnnnnnxxxxxxxxxxMMMMMMMMWWWWWWWWWWWWWW")
    print("@@@@WWWWWWWWWWWWMMMMMMMMMMMxxxxxxxxxxxnnnnnnnzzzzzzzzzzzzzzMWnMMxxxxxM @  # WMn*nMWW@@@WMMMMxxxnnWzzzz#zzzzzzzzzznnnnnnnnnnxxxxxxxxxxMMMMMMMWWWWWWWWWWWW")
    print("@@@WWWWWWWWWWWWMMMMMMMMxxxxxxxxxxxxxnnnnnnzzzzzzzzzzzzzzzzn @ xMWMMMxxxM  ##WW+ ,MM;+@##WMMMMMxxn@xz#######zzzzzzzzzznnnnnnnxxxxxxxxxxxMMMMWWWWWWWWWWWWW")
    print("@WWWWWWWWWWWWWWMMMMMMMxxxxxxxxxxxxxnnnnnzzzzzzzzzzzzzzzz  # zW@xWWWWWMMW#@@@W+ ,Mx``W@@#MMMMMMxxM@z############zzzzzznnnnnnnnnnxxxxxxxxMMMMMMWWWWWWWWWWW")
    print("WWWWWWWWWWWWWWMMMMMMxxxxxxxxxxxxnnnnnnnzzzzzzzzzzz  ##zzzz#x@MxW@W@WWW##@@@W# .Mn `M@@#WMMMMMMMx@x###############zzzzznnnnnnnnnnnxxxxxxMMMMMMMMWWWWWWWWW")
    print("WWWWWWWWWWWWWMMMMMMxxxxxxxxxxxnnnnnnnnzzzzzzz  # z######z#zz@@nMW@@@WWW##@W@W# `xn ,MW@@zMMMMMMMx@Wz################zzzznnnnnnnnnnnxxxxxxMMMMMMMMWWWWWWW")
    print("WWWWWWWWWWWWMMMMMMxxxxxxxxxxxxnnnnnnnzzzzzzz  ############x@MnMW@@@@WW##@WWW# `Mz :MWW@WMMMMMWMx@@x#################zzzznnnnnnnnnnxxxxxxMMMMMMMMMMMWWWWW")
    print("WWWWWWWWWWWMMMMMMxxxxxxxnnnnnnnnnnnzzzzzzz  ##############W@nxWW@@@@@W@@@WWW# `Mz ;MW@@@WMWWWWWxW#W#####+++++########zzzznnnnnnnnnnnxxxxxMMMMMMMMMMMWWWW")
    print("WWWWWWWWWWMMMMMMxxxxxxnnnnnnnnnnnnnzzzzz  ###########+###n@@nMWW@@@@@W@#@MWW+ `Mz :MW@@WMMWWWWWxM#@z+++++++++++#######zzzzznnnnnnnnnnxxxxxxMMMMMMMMMMWWW")
    print("WWWWWWWWWMMMMMMxxxxxxnnnnnnnnnnnnzzzzzzz  ##########++###x@WnMWWW@@@@WW@@MW@+ `Mz .xW@@MMMWWWW@xx@@n+++++++++++++######zzzzznnnnnnnnnnxxxxxxMMMMMMMMMMWW")
    print("WWWWWWWWMMMMMMxxxxxnnnnnnnnnnnnzzzzzzz  ##########+++####W@MzMWWW@@@@WW@WxW@# .Mz `nW@@WMMWWWW@xxW#M++++++++++++++######zzzzzznnnnnnnnnxxxxxxMMMMMMMMMWW")
    print("WWWWWWWMMMMMMxxxxxnnnnnnnnnnnnnzzzzzz  ###########+++###zW@xnMWWW@@@@@W@WnW@z ,Mz  zW@@@MMWWW@@xxM#W++++++++++++++#######zzzzzzzzzznnnnnxxxxxMMMMMMMMMMM")
    print("WWWWWWMMMMMMxxxxxnnnnnnnnnnnnzzzzzz  #########+##+++++##n@@nzMMWWWWW@@W@WnM@n :W# `xW@#@WMWWW@Wnnx@@#+++++++++++++########zzzzzzzzzznnnnnxxxxxMMMMMMMMMM")
    print("WWWWWMMMMMMxxxxxnnnnnnznnnzzzzzzzzz  ######+++++++++++++x@@z+xMxnxxxxxM#@zM@x ;W+ ,nMWMxnnxMW@Mnnx@@z+++++++++++++++#######zzzzzzzzzzznnnnnxxxxMMMMMMMMM")
    print("WWWWWMMMMMMxxxxnnnnnzzzzzzzzzzzzz  ######+++++++++++++++M@W#*nMn*nxnzzM@W;n@M`;W+ :#nzzzzzznzxxnnx@@n++++++++++++++++#+#####zzzzzzzzzzznnnnxxxxxMMMMMMMM")
    print("WWMMMMMMMMxxxxxnnnnzzzzzzzzzzzz  #######+++++++++++++++#W@M#zWW#xxnnnM@M# +@x.;Wi+Wxnnnnnnznz+Mxnx@@x+++++++++++++++++++#####zzzzzzzzzzznnnnxxxxxMMMMMMM")
    print("WWMMMMMMMxxxxxnnnnnzzzzzzzzzzz  ########+++++++++++++++#W@xnWWzxxxxx@#@M, *@n`,Wi@@x;:iMxnnnnzn@WW@@x+*++++++++++++++++++######zzzzzzzzzznnnnxxxxMMMMMMM")
    print("WMMMMMMMMxxxxnnnnnzzzzzzzzzzzz  #######++++++++++++++++zW@MWWnxxMMW@#@@M` *Wn``x#Wn+#x@@@@Wxnn#W@@#@M****++++++++++**++++#######zzzzzzzzzznnnnxxxxMMMMMM")
    print("WMMMMMMMxxxxnnnnnzzzzzzzzzzzzz  #######+++++++++++++++*z@@WWnMW@######@W#;#Wn;izn@##########WxznWW@@M+****++**++++++++++++#######zzzzzzzzznnnnxxxxxMMMMM")
    print("MMMMMMMxxxxnnnnnnzzzzzzzzzzz  ########++++++++++++++++*n@WWxM@############@###@@#############@MnWWMWM+********+++++++++++++########zzzzzzzzznnnxxxxxMMMM")
    print("MMMMMMMxxxxnnnnnzzzzzzzzzzz  ########++++++++++++++++++x@WWM@######@@@@########@###@WMMW@#####@MMWMMM+********+*+******++++###########zzzzzzznnnxxxxxMMM")
    print("MMMMMMxxxxxnnnnzzzzzzzzzz  #########++++++*+******+++++xMWM######@@###@@WW###@@@#@WMW@@@WW@#####MMWxx+**********+*******++++#############zzzzznnnxxxxxMM")
    print("MMMMMxxxxxnnnnzzzzzzzzz  ##########++++***********++++*xMM@####@@########@WW@#zxx@@@@@####@@####@MWMn+*******************+++++############zzzznnnnxxxxxx")
    print("MMMMxxxxxxnnnnzzzzzzzz  ##########++++**************++*xM@#####@###########@WMxzW@@@@@@####@@####@MWn+********************+++++##########zzzzznnnnnxxxxx")
    print("MMMMxxxxxnnnnzzzzzzz  ##########++++++****************+MW#####W###########@MM#+MMW#@##@@####@@####WMxz*****ii*************++++++++++######zzzzznnnnxxxxx")
    print("MMMxxxxxxnnnnzzzzzz  ##########+++++++****************zM@####@@############@MxzM@##@WWW@####@@####@MMn*iiiiiiiii************++++++++######zzzzzznnnnxxxx")
    print("MMxxxxxxnnnnzzzzzz  ###########+++++++****************MW#####@#####@########WxzM@##W###x@####@#####Wxn#iiiiiiiii**************++++++#######zzzzznnnnnxxx")
    print("Mxxxxxxnnnnnzzzzz  ##########+++++++++***************#M@#####@####@@########Wn+W@##M##zMW####@######MMziiiiiiiiii***************++++++#####zzzzznnnnnnxx")
    print("xxxxxxxnnnnnzzzz  ##########++++++++++***************MW######@@###M@#######@W@MW@##x#zzMM####W#######Mn*iiiiiiiii**i**************++++++####zzzznnnnnnnx")
    print("xxxxxxnnnnnzzzz  ########+++++++++++++**************+WW######@####M@@######@###W@##xzzxMM############Wx#iiiiiiiiii******************+++++###zzzzznnnnnnn")
    print("xxxxxxnnnnnzzzz  #######+++##++++++++*****ii********nW############@@#@@WMMxW###WW@@WMMM@@############@Mziiiiiiiiiii**i**************+++++####zzzzznnnnnn")
    print("xxxxxxnnnnnzzzzz  #####+++++++++++++****iiii********WW###########WMMMxnzznMW#@@@@#@@WxnznM############Wn*;;iiiiiiiiiiii*************++++++###zzzzznnnnnn")
    print("xxxxxxxnnnzzzzz  #####+++++++++++++****iiiii*i*****#@@#########@@WMnnnnnxxxM@MM@@@##@MW@@@#############x#;;;;iiiiiiiiiiii*************++++###zzzzzznnnnn")
    print("xxxxxxnnnnzzzzz  ###++++++++++++++****iiiiiiiii***in@#########@@WMMMMWWWWMW@M#z@@@@WW@@#####@##########Wni;;;;;iiiiiiiiiiiii**********++++####zzzzznnnnn")
    print("xxxxxxnnnnzzzz  ###++++++++++++++****iiiiiiiiii****W@#########xn@@#####@@M@Wi,;xWWzz+ii#xnnM@##########@x+;;;;;;;;iiiiiiiiiiiii******+++++####zzzzznnnnn")
    print("xxxxxnnnnzzzz  ####+++++++++++++*****iiiiiiiiii*ii#@@#########Wz#######@MMxx:;*zWMnn#i;+nnz#W###########Wz;;;;;;;;;iiiiiiiiiiii*******+++++####zzzznnnnn")
    print("xxxxxnnnnzzzz  ####+++++++++++++****iiiiiiiiiiiiiix@###########n@######@@nWn,;*#@WMz#i;+nnnn############@xi;;;;;;;;iiiiiiiiiiiiii*******++++###zzzznnnnn")
    print("xxxxxnnnnzzzz  ###+++++++++++++*****iiiiiiiiiiiii*W@###########MW#####W@Mn@M;:;z@WWx#i;#nnnM#############W+;;;;;;;;;iiiiiiiiiiiii*iii****+++###zzzzzznnn")
    print("xxxxnnnnzzzz  ####+++++++++++++****iiii;iiiiiiiii#@@###########@M####@@W#WW####@@#WMxn*znnn@#############@n;;;;;;;;;iiiiiiiiiiiiiiiiii****+++###zzzzzzzn")
    print("xxxxnnnnzzzz  ####+++++++++++++****iiii;iiiiiiiiix@#############M####@Wzx@##@#####@MWMWnznx###############M*;;;;;;;;;iiiiiiiiiiiiiiiii****+++###zzzzzzzn")
    print("xxxxnnnnzzzz  ###+++*+++++++++*****iiiiiiiiiiiiiiW@#############W@###Wnz@W##*@#n###WW@WWnzM######@########@z;;;;;;;;;;iiiiiiiiiiiiiiii****+++###zzzzzzzn")
    print("xxxxnnnnzzzz  ###+++++++++********iiiiiiiiiiiiii+@@##############W##@n#WW@#@+WW#####M@W@@n@#######@########xi;;;;;;;;;;iiiiiiiiiiiiiiiii***+++###zzzzzzn")
    print("xxxxnnnnzzzz  ##++++++++++********iiiiiiiiiiiiiin@###############W#@n#x@@MWM+Mx+@###@W#@@M#@######@########W#;;;;;;;;;;;;iiiiiiiiiiiiiiii***++###zzzzzzn")
    print("xxxxnnnzzzz  ###+++++++++++******iiiiiiiiiiiiiiiW@##############@Mnz+#@@##WM*xx+W@z##WW#@@WW###############@n;::;;;;;;;;;;iiiiiiiiiiiiiiii**++###zzzzzzz")
    print("xxxxnnnnzzz  ###++++++++********iiiii;;;;;;;;;;*@@#######@#######@WW#xW###nz*xz+xM+###W@Mnx@#@#####@#@#####Wx+:::;;;;;;;;;iiiiiii*iiiiiiii***+####zzzzzz")
    print("xxxxnnnnzzz  ###+++++++*********iiii;;;;;;;;;;;z@#######@@@####@@@WxW@zWMinn;nz*nz+W@@@@MzMW@@#####@@######@Mn;:::::;;;;;;;;iiiiiiiiiiiii****++###zzzzzz")
    print("xxxxnnnzzzz  ###++++++*+********iiii;;;;;;;;;;;x@#######@@@####@Mx:`x@#+#+##n##n#zx##*MWz#W@#####@@@@##@####@@*:::::;;;;;;;;;;iiiiii*iiiii***++###zzzzzn")
    print("xxxnnnnzzzz  ###++++**+*********iiii;;;;;;;;;;iM@######@@@@#####@zi:xWWWWWWWW@@@@#####@@,.M@#####@@@###@####@Wx;::::::;;;;;;;;iiiiii**iiii***++###zzzzzn")
    print("xxxnnnnzzzz  ###+++*************iii;;;;;;;;;;;#W@######@@@@####@WnzM@@@@@W@WWWWMMMxMMWWW#+xW@##########@@###@Mz+:::::::;;;;;;;iiiiii**********++##zzzzzz")
    print("xxxxnnnzzz  ###+++++*********iiiii;;;;;;;;;;;;#z@#@###@@@@@###@xnxnM@@@@MxnxnnxMxMxW#@##@xzM@@##########@####@++:::::::::;;;;;;;iiiiii********+++##zzzzz")
    print("xxxnnnnnzz  ###+++++++********iii;;;;;;;;;;;;;*z@@@##@W@@@####WMnW@W@##@@MnnnnnnnxM@#####MMWMW###############@x;::::::::::;;;;;;iiiiiii*******+++###zzzz")
    print("xxxnnnnzz  ####+++++++*******iii;;;;;;;;;;;;;;iz@W@##WWWW@###@@WWxWMW@##@@WnznznnW#@###@@@WWnM@###########@@##z,::::::::::::;;;;;iiiiiiii******++###zzzz")
    print("xxxnnnzzz  ####++++++*******iii;;;;;;;;;;;;;;:i+#@@#@WW@W@###@@@@nMWW@@##@@WnnnM@@@######@@xzM@##############M,,:::::::::::::;;;;;;iiiiiii*****+++##zzzz")
    print("xxxnnnzzz  ####+++++*******iii;;;;;;;;;;;::::::*M###W@@@W@###@WxxzMWWW@###@@WMW#@@#######@MnznM######@#####W+,:::::::::::::::;;;;;;;iiiiiiii***+++###zzz")
    print("xxxnnnzzz  ####+++++*******ii;;;;;;;;;:::::::::;+W##@@WWW@##Wz+*+#xW@@@@####@@#@@########@xzzzx@#@W#####Wzi,:,,,:::::::,::::::::;;;;;;iiiiii*****++###zz")
    print("xxxnnnzzz  ####+++++*****iiii;;;;::::::::::::::::in@###@@@#@*;i;i#xW@@####@WWW@@@@######@@nzzzx@@##@Mn+;:,,,,,,,,::::::,:::::::::;;;;;;iiiii*****++++##z")
    print("xxxnnzzz  #####+++++*****iii;;;;;::::::::::::::::,,:;+zxMW@W:,:;i#xW@@#####@@@WWWW@#@@@@@Wnz#zxn+i;::,,,,,,,,,,,,,:::::::::::::::::;;;;;;iiii****++++###")
    print("xxnnnzzz  #####+++++*****iii;;;;::::::::::::::::,,,,,,,,,,,:,`,;i#xWW@@@####@@@@@##@@@@@@MxnnnMMMW###Wx#i,,,,,,,,,:::::,,,,:::::::::;;;;iiiii*****++++##")
    print("xxnnnzzz  #####+++++*****iii;;;::::::::::;:::::::,,,,,,,,:+zz;`:izxMW@@@WWW@@@@W@@@WMWWWMxxxM@#####@@##@@x;,,,,,,,,::::,,,::::::::::;;;;iiiii*****++++##")
    print("xxxnnzzzz  ####+++++++***iii;;;;:::::;:;;;::::::,,,,,,,;z@###W,.;#xMWW@Wx*+zMMMMMWMxxxnxxxM@########@W@#@#Wi,,,,,,,:::::::,:::::::::;;;iiiiii*****++++##")
    print("xxnnzzzzzz  ###+++++++***iii;;;;::::;;;;;;::::,,,,,,,;zxx#####*.i+nMMW@@x*;;;+zzzzz+**zznW#@########@@@@@@#@n;,,,,,::::::::::::::::::;;;iiii*****++++###")
    print("xxnnzzzzz  #####+++++****iii;;;:::::;;;;;:::::,,,,,:#xx+x#####@+,***nMW@@WWWWMMMMMMni*xM@@@########MM@@@WW@@@@x+;:,:::::::::::::::::::;;iii*****+++++###")
    print("xxnnnzzzz  ######+++++**iii;;;;:::::;::;:::::,,,,,izx@Wix#######z:*#*#xW@@WWWWWWWWWWMWW@@@@#######@xxWW@WW@@@@@@@Wx#i:::::::::::::::::;;;i******+++++###")
    print("xxnnnzzzzz  #######+++***iii;;;::::;;;;;;::::,,,,+W:z@@*#########@xnnMnxW@@@@@@@@WMMM@WWW@@#######WWMMM@M@@@@@@@@WWWWx+:::::::::::::;;;;;ii*****+++++###")
    print("xxnnnzzzzz  ########++***ii;;::::::;;;;;;:::,,,;nMM;;W#n*z@#########@@WW@@@@@@@@WW@@WMW@@@#######@xxMxxMz@WW@@@@@WWWWWWM#;::::::;;;;;;;;iii*****++++####")
    print("xxnnnzzzzz  #######+++***ii;;:::::;;;;;;;:::,:+xMMMi,W@x@xx@###################@@@WMW@@@#######@MnnMMMxMWWWWW@@@WWWWWWWWWMz;::;;;;;;;;;;;ii****+++++####")
    print("xxnnnzzzzz  #######++++**ii;;;::::;;;;;;;:::*nxxxxM#*xz;M@@@@################@#@@@@#@@########W@nxxMnMnW@WWWWWWWWWWWWWWWWWWWz;;;;;;;;;;;iii***++++++####")
    print("xxnnnzzzz  ########++++**ii;;;;::;;;;;;;:;+nMMMxxMxMxM*;WMW@@#####################@@#########@WnzMMxzMxWWWWWWWWWWWWWWWWWWWWWWW+;;;;;iiiiii***++++++#####")
    print("xxnnnnzzz  #########+++**ii;;;;;;;;;;;;i#xxxxxxMWW@WM+xM@#@@@@@###############@###@########@WW@MznxMnMMWWWWMWWWWWWWWWWWWWWWWWWWziiiiiiii***+++++++######")
    print("xxxnnnzzz  ####zz###+++**ii;;;;;;;;;;*zxxxMMMW@WWMxMWW@####xM@@##@W@#####@W@WWMWMWW####@WWWxWWW#MznxMWWMWWMMWWWWWWWWWWWWWWWWWW@@niiiii****+++++++#######")
    print("xxxnnnzzz  ####z#####++**ii;;;;;;;i#xxxMMMWWWMMMWW@@@@@@#@MW@#@#@@@@#####@xMWMxxxnM@W@WW@WM@W@W##xzMWWWW@@WMMWWWWWWWWWWWWWWW@@@@@nii*****++++++#########")
    print("xxxnnnzzzzzzz  #####+++**ii;;;;;*nxxMMMMMMMMW@@@@###@@@WxnW#####@##@#@@@@@xxWMnxnzMWWxMMW@###@W@##MWWWWW@@@WWMWWWWWWWWWWWWW@@@@@@@x*****+++++++#########")
    print("xxxnnnzzzzzzz  #####+++**ii;;;;+xMMMMMxxMWW@#####@@@WMWWxW#####@W####@@@@#@W@WMWMxMWWW######Wx##@##@WWWW@@@@@WMWWWWWWWWWWWW@@@@@@@@x****++++++########zz")
    print("xxxnnnnzzzzzz  #####+++**iiiii*xMMMMMMMW@@@#@@@@WMMW@@@M@#####@W@########@@@@MxWMMW@########xx#@nM###W@W@@@@@@WWWWWWWWWWWWW@@@@@@@@@z****+++++########zz")
    print("xxxnnnnzzzzzz  #####+++***iii*nWWWWWWW@@@@@WMMMW@@@@@@@@###@@#@@@#########@nMxnMx#@#########zW#W+iz@##@WWW@@@#@@WWWWWWWWWW@@@@@@@@@@@+***+++++########zz")
    print("xxxnnnnzzzzzzz  #####+++**ii*nW@WWWWWWWWMMMMW@@@@@@@@@@##@WW@##@@#########@zxnzn#+@#########*@@ni,:+x@@@WWW@@@##@@W@@@@W@@@@@@@@@##@@W**++++++########zz")
    print("xxxxnnnnzzzzz  ######+++****nW@WWWWWWWWMMW@@@@@@@@@@@@##@xMMWW@@W#########@nxnzn#+@#########i#@#i,,,,;in@WWW@@@@##@W@@@@W@@@@@@@@###@#n++++++##########z")
    print("xxxxnnnnnzzzz  ######+++***zM@WW@@WWWWWW@@@@WWWWW@@@@#@WxnxMMx@@W#########@nxMzn++@########@+#W*;,,...` ;@WWWW@@@##@@@@@@@@@@@@@@####@@#+++++########zzz")
    print("xxxxxnnnnzzzz  #####++++**#M@WMW@@@W@@W@WWWWWW@@@@W@#WxnnnnxMxW@W##########xxM+n+#@########M+#M*;,,...` `Wz@WWW@@@##@@@@@@@@##@@@#####@W++++++######zzzz")
    print("Mxxxxnnnnzzzzz  #####+++++xW@WMW@@@@WWWWWWW@@@@@@W@##nzznnnxxxx@W@#########MxM;n+#@########x##ni:,,...  .x`#@WWW@####@@@@@@####@@#######n+++++######zzzz")
    print("MMxxxnnnnzzzz  ######++++zM@WMMW@@@@WWWWWW@@@@@WW####n####znnnn@@@#########MxM;x+#@########xz@#i:,,.,.  :n  z@WW@#####@@@@@####@@#######@#++++#######zzz")
    print("MMxxxxnnnnzzz  ######+++#n@@WMMW@@@@WWWWW@@@@WW@#####x**++##zznM@@#########WxM;x#z@#W#####z##@+;:,,,,.  i#  `@@WW@@####@@@@#####@########x+++++++####zzz")
    print("MMxxxxnnnnzzz  ######+++nM#@WMMW@@WWWWWW@@@@MW@###@##W**++##zznx@@#########WxM;x#z@@@###@@ix#@+;,,,,,,` +i  .xxW@@@@####@##################++++++####zzz")
    print("MMxxxxnnnzzz  ######+++znW#@MMMWWWW@WW@@##@WM@##@@WWW@+**+###zzn@##########@xM;xzzM`z#@M;n*W#W+:,,,,,,. #:  ,n.MW@@@@@####################M++++++#####zz")
    print("MMxxxxxnnzzz  ###++++++nx##@MMWWWWW@WW@@#@WM@##nxWW@#@#+++###z#zW##########@xM;xzzx n#@x,,*W#W+:,,,,,,.`n.  :n ,@@@@@@@####################z++########zz")
    print("MMxxxxxnnzz  ####+++++zMM##WMWWWMWW@W@@#@WM@##n+z@@@#@n+++#####zW#######@#@@MM;xzz# x##@#`:@zW+;,,,,,,,,x   iz  i@@@@@@@###################W##########zz")
    print("MMMxxxxnnzz  #####++++nWW##WMW@WxMW@W@@#@MW##M#+#@@##Wx+++++###zM##@###@M,@@MW;xzn+ n###x`:W#W+;,,,,,,,,n   xz   +#@@@@#####################n#########zz")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
    print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
"""  #Desative o comentário para visualizar o Darth Vader!!!
